// Copyright 2019 Blues Inc.  All rights reserved.
// Use of this source code is governed by licenses granted by the
// copyright holder including that found in the LICENSE file.

package note

// DeviceSession is the basic unit of recorded device usage history
type DeviceSession struct {
	// Session ID that can be mapped to the events created during that session
	SessionUID string `json:"session,omitempty"`
	// Info from the device structure
	DeviceUID  string `json:"device,omitempty"`
	DeviceSN   string `json:"sn,omitempty"`
	ProductUID string `json:"product,omitempty"`
	FleetUID   string `json:"fleet,omitempty"`
	// IP address of the session
	Addr string `json:"addr,omitempty"`
	// Cell ID where the session originated and quality ("mcc,mnc,lac,cellid")
	CellID string `json:"cell,omitempty"`
	// Parameters passed by device as a result of scanning towers/APs
	ScanResults *[]byte
	Triangulate *map[string]interface{} `json:"triangulate,omitempty"`
	// Signal strength/quality of the cell
	Rssi int    `json:"rssi,omitempty"`
	Sinr int    `json:"sinr,omitempty"`
	Rsrp int    `json:"rsrp,omitempty"`
	Rsrq int    `json:"rsrq,omitempty"`
	Rat  string `json:"rat,omitempty"`
	// Last known tower location at beginning of session
	Tower TowerLocation `json:"tower,omitempty"`
	// Last known GPS location extracted from data flowing through session
	WhereWhen     int64   `json:"where_when,omitempty"`
	WhereOLC      string  `json:"where,omitempty"`
	WhereLat      float64 `json:"where_lat,omitempty"`
	WhereLon      float64 `json:"where_lon,omitempty"`
	WhereLocation string  `json:"where_location,omitempty"`
	WhereCountry  string  `json:"where_country,omitempty"`
	WhereTimeZone string  `json:"where_timezone,omitempty"`
	// Log key for this session
	SessionLogKey string `json:"session_log_key,omitempty"`
	// Total device usage at the beginning of the period
	This DeviceUsage `json:"this,omitempty"`
	// Total device usage at the beginning of the next period, whenever it happens to occur
	Next DeviceUsage `json:"next,omitempty"`
	// Usage during the period - initially estimated, but then corrected when we get to the next period
	Period DeviceUsage `json:"period,omitempty"`
	// Flag indicating whether the usage data is based on actual stats from the device
	IsUsageActual bool `json:"usage_actual,omitempty"`
	// Physical device info
	Voltage float64 `json:"voltage,omitempty"`
	Temp    float64 `json:"temp,omitempty"`
	// Type of session
	ContinuousSession bool `json:"continuous,omitempty"`
	TLSSession        bool `json:"tls,omitempty"`
	// For keeping track of when the last work was done for a session
	LastWorkDone int64 `json:"work,omitempty"`
	// Number of Events routed
	EventCount int64 `json:"events,omitempty"`
	// Motion of the notecard
	Moved       int64  `json:"moved,omitempty"`
	Orientation string `json:"orientation,omitempty"`
	// Why a session was triggered
	Trigger string `json:"trigger,omitempty"`
}

// TowerLocation is the cell tower location structure generated by the tower utility
type TowerLocation struct {
	When        int64   `json:"time,omitempty"` // time when this location was ascertained
	Name        string  `json:"n,omitempty"`    // name of the location
	CountryCode string  `json:"c,omitempty"`    // country code
	Lat         float64 `json:"lat,omitempty"`  // latitude
	Lon         float64 `json:"lon,omitempty"`  // longitude
	TimeZone    string  `json:"zone,omitempty"` // timezone name
	MCC         int     `json:"mcc,omitempty"`
	MNC         int     `json:"mnc,omitempty"`
	LAC         int     `json:"lac,omitempty"`
	CID         int     `json:"cid,omitempty"`
	OLC         string  `json:"l,omitempty"`      // open location code
	TimeZoneID  int     `json:"z,omitempty"`      // timezone id (see tz.go)
	Count       int64   `json:"count,omitempty"`  // number of times this location was recently used
	Towers      int     `json:"towers,omitempty"` // number of triangulation points
}
