# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.7
    working_directory: /go/src/github.com/blues/note-go
    steps:
      - checkout
      - run: mkdir artifacts
      - run:
          name: Build all executable binaries. (note, notehub, notecard, ...)
          environment:
            GO111MODULE: "on"
          command: find * -name 'main.go' -execdir go build -x -o "$(pwd)/artifacts/" \;
      - store_artifacts:
          path: artifacts

