# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.7
    working_directory: /go/src/github.com/blues/note-go
    persist_to_workspace: ./artifacts/
    steps:
      - checkout
      - run: mkdir -p ./artifacts/
      - run:
          name: Build all executable binaries. (note, notehub, notecard, ...)
          environment:
            GO111MODULE: "on"
          command: find * -name 'main.go' -execdir go build -x -o "$(pwd)/artifacts/" \;
      - store_artifacts:
          path: artifacts
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    requires:
      - build
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="$(git describe --dirty)"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
