# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.7
    working_directory: /go/src/github.com/blues/note-go
    steps:
      - checkout
      - run: mkdir -p ./artifacts/
      - run:
          name: Build all executable binaries. (note, notehub, notecard, ...)
          environment:
            GO111MODULE: "on"
          command: find * -name 'main.go' -execdir go build -x -o "$(pwd)/artifacts/" \;
      - store_artifacts:
          path: ./artifacts/
      - persist_to_workspace:
          root: .
          paths: ./artifacts/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      # We need to do a checkout so the CIRCLE_PROJECT_REPONAME and CIRCLE_SHA1 vars are populated for the command below.
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run: ls -l ./artifacts/
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="$(git describe --dirty)"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              # match 1.2.3 etc. i.e. only tags that look like they're tagging a release.
              only: /^\d+\.\d+\.\d+$/

