// Copyright 2025 Blues Inc.  All rights reserved.
// Use of this source code is governed by licenses granted by the
// copyright holder including that found in the LICENSE file.

package api

// Current data format of the reconciliation job type.  Note that major types
// require conversion, while minor types can be handled by the same code.
const HubJobReconciliationMajorVersion = 1
const HubJobReconciliationMinorVersion = 1

// HubJobReconciliation is the format of a batch request file
type HubJobReconciliation struct {
	Header  HubJob `json:"job,omitempty"`
	Comment string `json:"comment,omitempty"`
	Select  struct {
		Comment         string   `json:"comment,omitempty"`
		AllDevices      bool     `json:"all_devices,omitempty"`
		DevicesInFleets []string `json:"devices_in_fleets,omitempty"`
		Devices         []string `json:"devices,omitempty"`
		DevicesBySn     []string `json:"devices_by_sn,omitempty"`
	} `json:"select,omitempty"`
	DefaultRequests HubJobReconciliationRequests            `json:"default_requests,omitempty"`
	DeviceRequests  map[string]HubJobReconciliationRequests `json:"device_requests,omitempty"`
	ReportOptions   HubJobReconciliationReportOptions       `json:"report_options,omitempty"`
}

// HubReportReconciliation is the format of the report generated by a reconciliation job.
type HubReportReconciliation struct {
	Comment string                           `json:"comment,omitempty"`
	Header  HubJobReport                     `json:"job,omitempty"`
	Status  HubJobReconciliationReportStatus `json:"status,omitempty"`
	Report  *HubJobReconciliationReport      `json:"output,omitempty"`
}

// HubJobReconciliationRequests is a structure defining requests to apply to a set of selected devices.
// Note that if ProvisionProductUID is specified, the device will be provisioned if it isn't already provisioned,
// else it will fail if not provisioned.  Also note that sn_to_set and vars_to_set use the same syntax
// as our standard API calls in that the value '-' means to clear the value.
type HubJobReconciliationRequests struct {
	Comment             string            `json:"comment,omitempty"`
	ProvisionProductUID string            `json:"provision_product,omitempty"`
	Disable             bool              `json:"disable,omitempty"`
	Enable              bool              `json:"enable,omitempty"`
	CaDisable           bool              `json:"connectivity_assurance_disable,omitempty"`
	CaEnable            bool              `json:"connectivity_assurance_enable,omitempty"`
	SnToDefault         string            `json:"sn_to_default,omitempty"`
	SnToSet             string            `json:"sn_to_set,omitempty"`
	VarsToDefault       map[string]string `json:"vars_to_default,omitempty"`
	VarsToSet           map[string]string `json:"vars_to_set,omitempty"`
	FleetsToDefault     []string          `json:"fleets_to_default,omitempty"`
	FleetsToJoin        []string          `json:"fleets_to_join,omitempty"`
	FleetsToLeave       []string          `json:"fleets_to_leave,omitempty"`
}

// HubJobReconciliationReportStatus is the status portion of a batch report file
type HubJobReconciliationReportStatus struct {
	Error       string            `json:"error,omitempty"`
	Errors      map[string]string `json:"errors,omitempty"`
	Actions     map[string]string `json:"actions,omitempty"`
	DeviceCount int               `json:"device_count,omitempty"`
	Provisioned []string          `json:"provisioned,omitempty"`
}

// HubJobReconciliationReport is the format of a batch report file
type HubJobReconciliationReport struct {
	App     *HubJobReconciliationAppReport              `json:"project,omitempty"`
	Devices map[string]HubJobReconciliationDeviceReport `json:"devices,omitempty"`
}

// HubJobReconciliationReportOptions is a structure defining options for the report
type HubJobReconciliationReportOptions struct {
	Comment        string `json:"comment,omitempty"`
	AppInfo        bool   `json:"app_info,omitempty"`
	AppVars        bool   `json:"app_vars,omitempty"`
	AppFleets      bool   `json:"app_fleets,omitempty"`
	DeviceInfo     bool   `json:"device_info,omitempty"`
	DeviceActivity bool   `json:"device_activity,omitempty"`
	DeviceHealth   bool   `json:"device_health,omitempty"`
	DeviceVars     bool   `json:"device_vars,omitempty"`
}

// HubJobReconciliationAppReport is a structure defining the app report
type HubJobReconciliationAppReport struct {
	Info   *GetAppResponse                     `json:"project_info,omitempty"`
	Vars   *GetAppEnvironmentVariablesResponse `json:"project_vars,omitempty"`
	Fleets *GetFleetsResponse                  `json:"project_fleets,omitempty"`
}

// HubJobReconciliationDeviceReport is a structure defining the device report
type HubJobReconciliationDeviceReport struct {
	Info *GetDeviceResponse                     `json:"device_info,omitempty"`
	Vars *GetDeviceEnvironmentVariablesResponse `json:"device_vars,omitempty"`
}
