// Copyright 2025 Blues Inc.  All rights reserved.
// Use of this source code is governed by licenses granted by the
// copyright holder including that found in the LICENSE file.

package api

// HubJobSmartFleet is the format of a smart fleet evaluation job request
type HubJobSmartFleet struct {
	Header   HubJob `json:"job,omitempty"`
	Comment  string `json:"comment,omitempty"`
	FleetUID string `json:"fleet_uid"`
}

// HubReportSmartFleet is the format of the report generated by a smart fleet evaluation job
type HubReportSmartFleet struct {
	Comment string                       `json:"comment,omitempty"`
	Header  HubJobReport                 `json:"job,omitempty"`
	Status  HubJobSmartFleetReportStatus `json:"status,omitempty"`
}

// HubJobSmartFleetReportStatus is the status portion of a smart fleet evaluation report
type HubJobSmartFleetReportStatus struct {
	Error            string   `json:"error,omitempty"`
	DeviceCount      int      `json:"device_count,omitempty"`
	DevicesAdded     []string `json:"devices_added,omitempty"`
	DevicesRemoved   []string `json:"devices_removed,omitempty"`
	DevicesUnchanged int      `json:"devices_unchanged,omitempty"`
	DevicesSkipped   int      `json:"devices_skipped,omitempty"`
}
