name: PR Checks
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: install dependencies
        run: apt update && apt install -y git gcc

      - name: go build
        run: |
          go build ./...